export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const BOOK_SUCCESS = "BOOK_SUCCESS";
export const BOOKS_SUCCESS = "BOOKS_SUCCESS";
export const BOOK_FAILURE = "BOOK_FAILURE";